### ISSUE TITLE
Open source: Please comply with the GWN licence

### ISSUE THREAD

**Issue by Dandigit** [BonfireScratch/N-PythonIntepreter#1]
I see you've used some code from GWN in your project.

GWN is licenced under the MIT licence, which comes with a lot of freedom, and just one term.
To comply, please:
- include and preserve [this notice](https://github.com/SimpleBinary/GWN/blob/master/license.md) in your code.

**Comment by Dandigit** [comment]
@SimpleBinary ?? That's not a requirement of the license. MIT is permissive.

**Comment by BonfireScratch** [comment]
I am sorry about it. I was planning ton add some other features, but I got lazy

**Comment by BonfireScratch** [comment]
@Dandigit What do you mean?

**Comment by BonfireScratch** [comment]
@SimpleBinary I have got a question about your website

**Comment by SimpleBinary** [comment]
@Dandigit Oops, misread it.

**Comment by SimpleBinary** [comment]
@BonfireScratch What is the question about my website?

**Comment by BonfireScratch** [comment]
Whats the code for downloading?
